# preload wallpapers
preload = /home/void/Pictures/Wallpaper/Kath.png
preload = /home/void/Pictures/Wallpaper/srev.png

# assign to monitor
wallpaper = eDP-1,/home/void/Pictures/Wallpaper/Kath.png

# misc options
ipc = on
splash = false

